### ISSUE TITLE
Support FiniteSet

### ISSUE THREAD

**Issue by softaria-roman** [softaria/semantic-math-processor-client#4]
SYMPY UNSUPPORTED INPUT as JSON:
```
{"type":"structure","name":"interval","symbols":{},"errors":[],"intervalType":"closed","leftBound":{"type":"structure","name":"logarithm","symbols":{},"errors":[],"base":{"type":"structure","name":"number","symbols":{"symbols":[]},"errors":[],"value":"0.00"},"operand":{"type":"structure","name":"number","symbols":{"symbols":[]},"errors":[],"value":"34.01"}},"rightBound":{"type":"structure","name":"functionDifference","symbols":{},"errors":[],"func":{"type":"structure","name":"variable","symbols":{"comma":[]},"errors":[],"indexes":[],"value":"psi","isGreek":true},"upLimitValue":{"type":"structure","name":"constant","symbols":{},"errors":[],"value":"imaginaryUnit"},"downLimitValue":{"type":"structure","name":"variable","symbols":{"comma":[]},"errors":[],"indexes":[],"value":"t","isGreek":false}}}
```
PREPARED: 
```
{"token":{"type":"Interval","args":[{"type":"log","args":[{"type":"Float","args":[{"type":"$String","v":"34.01"}]},{"type":"Integer","args":[{"type":"$String","v":"0"}]}]},{"type":"Add","args":[{"type":"$Method","args":[{"type":"Symbol","args":[{"type":"$String","v":"'t'"}]},{"type":"$String","v":"I"}],"object":{"type":"Symbol","args":[{"type":"$String","v":"'psi'"}]},"method":"subs"},{"type":"Mul","args":[{"type":"Integer","args":[{"type":"$String","v":"-1"}]},{"type":"$Method","args":[{"type":"Symbol","args":[{"type":"$String","v":"'t'"}]},{"type":"Symbol","args":[{"type":"$String","v":"'t'"}]}],"object":{"type":"Symbol","args":[{"type":"$String","v":"'psi'"}]},"method":"subs"}]}]}]}}
```
WAS SENT TO SYMPY: 
```
Interval(log(Float(34.01),Integer(0)),Add((Symbol('psi')).subs(Symbol('t'),I),Mul(Integer(-1),(Symbol('psi')).subs(Symbol('t'),Symbol('t')))))```

**Comment by softaria-roman** [comment]
```
RAW RESULT FROM SYMPY: Contains(Mul(Integer(86), Symbol('u')), FiniteSet(Integer(4)))
SYMPY UNSUPPORTED INPUT as JSON:{"type":"structure","name":"includeSet","symbols":{},"errors":[],"fexp":{"type":"structure","name":"implicitMultiply","symbols":{},"errors":[],"left":{"type":"structure","name":"number","symbols":{"symbols":[]},"errors":[],"value":"86"},"right":{"type":"structure","name":"variable","symbols":{"comma":[]},"errors":[],"indexes":[],"value":"u","isGreek":false}},"set":{"type":"structure","name":"interval","symbols":{},"errors":[],"intervalType":"closed","leftBound":{"type":"structure","name":"number","symbols":{"symbols":[]},"errors":[],"value":"4"},"rightBound":{"type":"structure","name":"number","symbols":{"symbols":[]},"errors":[],"value":"4"}}}
PREPARED: {"token":{"type":"$Method","args":[{"type":"Mul","args":[{"type":"Integer","args":[{"type":"$String","v":"86"}]},{"type":"Symbol","args":[{"type":"$String","v":"'u'"}]}]}],"object":{"type":"Interval","args":[{"type":"Integer","args":[{"type":"$String","v":"4"}]},{"type":"Integer","args":[{"type":"$String","v":"4"}]}]},"method":"contains"}}
WAS SENT TO SYMPY: (Interval(Integer(4),Integer(4))).contains(Mul(Integer(86),Symbol('u')))
  1) tests sympy client include[86@lvar[u],ci[4,4]]
```

**Comment by softaria-roman** [comment]
1) tests sympy client include[86@lvar[u],ci[4,4]]:
     AssertionError: Unsupported constructionFiniteSet/Unknown function: FiniteSet(Integer(4))/Contains(Mul(Integer(86),Symbol('u')),FiniteSet(Integer(4)))
      at Context.<anonymous> (tsOutputs/test/sympy-client-bdd.js:72:40)
      at Generator.throw (<anonymous>)
      at rejected (tsOutputs/test/sympy-client-bdd.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by softaria-roman** [comment]
1) tests sympy client ci[const[e],const[e]] ∪ ∅ ∩ ∅:
     AssertionError: Unsupported constructionFiniteSet/Unknown function: FiniteSet(E)/FiniteSet(E)
      at Context.<anonymous> (tsOutputs/test/sympy-client-bdd.js:72:40)
      at Generator.throw (<anonymous>)
      at rejected (tsOutputs/test/sympy-client-bdd.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
